// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjOAg1yQuIDQu6c0OqHeNgj14ZtCoDXM',
    appId: '1:236875411266:web:7d8e7806bd8475ab8da2db',
    messagingSenderId: '236875411266',
    projectId: 'momento-dfcdf',
    authDomain: 'momento-dfcdf.firebaseapp.com',
    storageBucket: 'momento-dfcdf.appspot.com',
    measurementId: 'G-S3N94ZQG2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByrFrTeHfP0t_yXQfa6sjSDJuwKIX5Dyg',
    appId: '1:236875411266:android:db7b5657c7e965868da2db',
    messagingSenderId: '236875411266',
    projectId: 'momento-dfcdf',
    storageBucket: 'momento-dfcdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJpjO8i0KkuErRKdTKlYAGtd2VFAPAHM',
    appId: '1:236875411266:ios:7047df8f8dd0e11c8da2db',
    messagingSenderId: '236875411266',
    projectId: 'momento-dfcdf',
    storageBucket: 'momento-dfcdf.appspot.com',
    iosBundleId: 'com.example.momentoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqJpjO8i0KkuErRKdTKlYAGtd2VFAPAHM',
    appId: '1:236875411266:ios:7047df8f8dd0e11c8da2db',
    messagingSenderId: '236875411266',
    projectId: 'momento-dfcdf',
    storageBucket: 'momento-dfcdf.appspot.com',
    iosBundleId: 'com.example.momentoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqjOAg1yQuIDQu6c0OqHeNgj14ZtCoDXM',
    appId: '1:236875411266:web:92bba8e59b88346e8da2db',
    messagingSenderId: '236875411266',
    projectId: 'momento-dfcdf',
    authDomain: 'momento-dfcdf.firebaseapp.com',
    storageBucket: 'momento-dfcdf.appspot.com',
    measurementId: 'G-D4TW55N6BD',
  );
}
